[workspace]
members = [
  "packages/enclave-ffi-types",
  "packages/schema",
  "packages/sgx-vm",
  "packages/shared/*",
  "packages/std",
  "packages/storage",
  "packages/cosmwasm-proto",
]
exclude = ["contracts", "packages/wasmi-runtime", "packages/enclaves", "packages/enclave-test"]
