[package]
name = "cosmwasm-proto"
version = "1.2.4"
authors = ["bob"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "cosmwasm_proto"
crate-type = ["staticlib"]

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false

[features]
build-protobuf = ["protoc-rust", "dirs"]

[dependencies]
protobuf = { version = "2.25.2", features = ["with-serde"]}

[build-dependencies]
protoc-rust = { version = "=2.25", optional = true }
dirs = { version = "3.0", optional = true }
glob = "0.3.0"
