# This file is an example config file for Rumor

query_gas_limit = 300000

inter_block_cache = true

tendermint_endpoint = "localhost:26667"

sync_until = 0

db_dir = "data"

genesis_path = "genesis.json"

lcd_port = 8080

home = ".secretd"
