[package]
name = "enclave_crypto"
version = "1.2.4"
authors = ["Cashmaney <itzik@enigma.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
aes-siv = "=0.6.2"
enclave-ffi-types = { path = "../../enclave-ffi-types" }
ring = { git = "https://github.com/mesalock-linux/ring-sgx", tag = "v0.16.5" }
sgx_types = { rev = "a37ffb9449ba6d5b6e4a9d586bbab864ae732269", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = {rev = "a37ffb9449ba6d5b6e4a9d586bbab864ae732269", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = [
  "backtrace"
] }
sgx_trts = {rev = "a37ffb9449ba6d5b6e4a9d586bbab864ae732269", git = "https://github.com/apache/teaclave-sgx-sdk.git" }

ripemd160 = "0.9.1"
secp256k1 = "0.19.0"
x25519-dalek = { version = "=1.2.0", default-features = false, features = [
  "u64_backend"
] }
sha2 = "0.8.1"
derive_more = "0.99"
lazy_static = "1.4"
hex = "0.4.2"

[patch.crates-io]
rand_core = { git = "https://github.com/mesalock-linux/rand-sgx", default-features = false, features = [
  "mesalock_sgx"
] }
